### PR TITLE
Update Runtime(s) to 23.08

### PR DESCRIPTION
**Pull request by Justinzobel**

### CODE REVIEW

**Comment by Justinzobel** [comment]
bot, build

**Comment by tsdgeos** [comment]
bot, build

**Comment by travier** [comment]
https://invent.kde.org/sdk/ikona Ikona has been archived so we can probably leave this one as is?

**Comment by tsdgeos** [comment]
Yes, i didn-t realize it was marked as archived, question is if we should mark this somehow too as archived?

**Comment by travier** [comment]
Maybe https://docs.flathub.org/docs/for-app-authors/maintenance#end-of-life ? Or we just leave it as is.

**Comment by tsdgeos** [comment]
Maybe let's just leave it as it is for the time being, if there's someone using it, it's not like they are vulnerable to attacks or anything, it's a really simple app

**Comment by Justinzobel** [comment]
I think we should EOL it. Only active projects should be on Flathub in my opinion.

**Comment by Justinzobel** [comment]
Going to close this unless anyone wants to take it on. Project is archived, no future updates.

**Pull request closed without merging**
